version: '3.1'

services:
  db:
    image: postgres
    container_name: manushaidb
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: manushai
      POSTGRES_PASSWORD: sadat@642
      POSTGRES_USER: root
    volumes:
      - "pgvol:/var/lib/postgresql/data"
  adminer:
    image: adminer
    container_name: adminerpg
    restart: always
    ports:
      - 8081:8080
  redis:
    image: redis
    container_name: manushai-redis
    volumes:
      - redis_data:/data
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: manushai-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  pgvol:
  redis_data: